# Generated by Django 2.1.5 on 2025-10-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='nickName',
        ),
    ]
