# Generated by Django 2.1.5 on 2025-10-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20251011_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='focused_cities',
            field=models.TextField(default=[]),
        ),
        migrations.AddField(
            model_name='user',
            name='focused_constellations',
            field=models.TextField(default=[]),
        ),
        migrations.AddField(
            model_name='user',
            name='focused_stocks',
            field=models.TextField(default=[]),
        ),
    ]
