# Generated by Django 2.1.5 on 2025-10-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20251011_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickName',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
