# Generated by Django 2.1.5 on 2025-10-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20251012_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickName',
            field=models.CharField(max_length=256),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['nickName'], name='authorizati_nickNam_5ccced_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['open_id', 'nickName'], name='authorizati_open_id_d12299_idx'),
        ),
    ]
