# Generated by Django 2.1.5 on 2025-10-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
        ('authorization', '0005_auto_20251012_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='menu',
            field=models.ManyToManyField(to='apis.App'),
        ),
    ]
